<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RootNamespace>Simulator_best</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Simulator\ICD\SateliteUp.json">
      <Link>ICD\SateliteUp.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
    <PackageReference Include="PhantomLibrary" Version="1.0.0" />
  </ItemGroup>

</Project>
